apiVersion: apps/v1
kind: Deployment
metadata:
  name: genui
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: genui
  template:
    metadata:
      labels:
        app: genui
    spec:
      containers:
      - name: genui
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        args:
        - "--listen"
        ports:
        - containerPort: 7860
          name: webui
        - containerPort: 5000
          name: api
        - containerPort: 5005
          name: api-stream
        volumeMounts:
        - name: genui-pvc
          mountPath: /app/loras
          subPath: loras
        - name: genui-pvc
          mountPath: /app/models
          subPath: models
      volumes:
        - name: genui-pvc
          persistentVolumeClaim:
            claimName: genui-pvc