apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: cloudflare-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lloydmalin15@gmail.com # Your email
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
    - dns01:
        cloudflare:
          email: lloydmalin15@gmail.com
          apiTokenSecretRef:
            name: cloudflare-api-token # cloudflare api token
            key: api-token