apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-tools
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: it-tools
  template:
    metadata:
      labels:
        app: it-tools
    spec:
      containers:
      - name: it-tools
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80