{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/hmalin/k3s-argo.git' # UPDATE THIS URL
    path: apps/{{ .name }}
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}