{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  source:
    {{- if .path }}
    # For charts stored in your Git repository
    repoURL: 'https://github.com/hmalin/k3s-argo.git'
    path: {{ .path }}
    targetRevision: HEAD
    {{- else }}
    # For charts from an external Helm repository
    repoURL: {{ .repo }}
    chart: {{ .chart }}
    targetRevision: {{ .version }}
    helm:
      values: |
        {{- toYaml .values | nindent 8 }}
    {{- end }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}