{{- range .Values.applications }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .name }}
  namespace: argocd
spec:
  project: default
  source:
    {{- if eq .type "helm-repo" }}
    # Logic for external Helm charts
    repoURL: {{ .repo }}
    chart: {{ .chart }}
    targetRevision: {{ .version }}
    helm:
      values: |
        {{- toYaml .values | nindent 8 }}
    {{- else }}
    # Logic for anything in the Git repo
    repoURL: 'https://github.com/hmalin/k3s-argo.git'
    path: {{ .path }}
    targetRevision: HEAD
    {{- if eq .type "helm-git" }}
    # Add the helm block only if it's a Helm chart in Git
    helm: {}
    {{- end }}
    {{- end }}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: {{ .namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{- end }}