{{- $nginx := .Values.applications.nginx }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $nginx.name }}
  namespace: argocd
spec:
  project: default
  source:
    repoURL: {{ $nginx.repoURL }}
    targetRevision: {{ $nginx.targetRevision }}
    path: {{ $nginx.path }}
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ $nginx.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true