# infra/argocd/values.yaml
applications:
  # Type 1: A Helm chart from your Git repo
  - name: nginx
    namespace: nginx-prod
    path: apps/nginx
    type: helm-git

  # Type 2: A Helm chart from an external repo
  - name: cert-manager
    namespace: cert-manager
    repo: https://charts.jetstack.io
    chart: cert-manager
    version: v1.18.2
    type: helm-repo
    values:
      installCRDs: true

  # Type 3: Plain YAML files from Git repo
  - name: cluster-issuers
    namespace: cert-manager
    path: cluster-config/issuers
    type: plain-git